# Generated by Django 3.0.5 on 2022-08-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=200)),
                ('testcatorgy', models.CharField(max_length=200)),
                ('testmaterials', models.FileField(upload_to='')),
                ('testlink', models.CharField(max_length=200)),
            ],
        ),
    ]
